# Javascript Node CircleCI 2.0 configuration file
# Reference https://circleci.com/docs/2.1/language-javascript/
version: 2.1

executors:
  nodejs:
    docker:
      - image: circleci/node:12.16

references:
  save_package_cache: &save_package_cache
    key: v1-dependencies-{{ checksum "yarn.lock" }}
    paths:
      - ./node_modules

  restore_package_cache: &restore_package_cache
    key: v1-dependencies-{{ checksum "yarn.lock" }}

commands:
  install:
    description: "Install dependencies"
    steps:
      - checkout
      - restore_cache: *restore_package_cache
      - run: yarn install --frozen-lockfile
      - save_cache: *save_package_cache

  npm-publish:
    steps:
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > .npmrc
      - run:
          name: Publish package
          command: npm publish

jobs:
  test-and-audit:
    executor: nodejs
    steps:
      - install
      - run: yarn test
      - run: yarn lint
      - run: yarn format:check
      - run: .circleci/yarn-audit.sh

  deploy-storybook-preview:
    executor: nodejs
    steps:
      - install
      - run: yarn build:storybook
      - run: npx netlify-cli deploy --prod
    environment:
      NETLIFY_SITE_ID: "cffa1ae2-c3a1-4c6d-b964-f218b10d6fbe"

  release-and-publish:
    executor: nodejs
    steps:
      - install
      - run: yarn build
      - npm-publish

workflows:
  version: 2
  test-build-release:
    jobs:
      - test-and-audit:
          filters:
            tags:
              only: /.*/

      - release-and-publish:
          context: IGG
          requires:
            - test-and-audit
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/

      - deploy-storybook-preview:
          context: IGG
          requires:
            - test-and-audit
          filters:
            branches:
              only: master
